import { existsSync } from 'node:fs';
import path from 'node:path';
import routes from './routes.json' with { type: 'json' };
export const knownRoutes = routes;
const slugs = ['brothersfix','allure-dispatch','quickworx','iyurek'];
const own = (object, keys, label) => {
  if (!object || typeof object !== 'object' || Array.isArray(object)) throw new Error(`${label} must be an object.`);
  for (const key of Object.keys(object)) if (!keys.includes(key)) throw new Error(`Unknown field: ${label}.${key}`);
  for (const key of keys) if (!(key in object)) throw new Error(`Missing field: ${label}.${key}`);
};
const text = (value, label, max=1000, empty=false) => { if (typeof value !== 'string' || (!empty && !value.trim()) || value.length>max || value.includes('\0')) throw new Error(`${label} must be ${empty?'0':'1'}–${max} characters.`); };
const bool=(value,label)=>{if(typeof value!=='boolean')throw new Error(`${label} must be true or false.`);};
const list=(value,label,max=30)=>{if(!Array.isArray(value)||!value.length||value.length>max)throw new Error(`${label} needs 1–${max} entries.`);value.forEach(v=>text(v,label,4000));};
const https=(value,label)=>{text(value,label,1000);let u;try{u=new URL(value);}catch{throw new Error(`${label} must be a valid HTTPS URL.`);}if(u.protocol!=='https:'||u.username||u.password)throw new Error(`${label} must be a public HTTPS URL without credentials.`);return u;};
function asset(value,label,root){text(value,label,500);if(value==='/opengraph-image')return;if(!/^\/(?!\/)[a-zA-Z0-9_./ -]+\.(png|jpe?g|webp|avif)$/i.test(value)||value.includes('..')||!existsSync(path.join(root,'public',value)))throw new Error(`${label} must reference an existing local PNG, JPEG, WebP or AVIF image.`);}
export function validateContent(data,root=process.cwd()) {
  own(data,['version','site','profile','pages','projects'],'content');if(data.version!==1)throw new Error('Unsupported content version.');
  own(data.site,['url','index','googleVerification','bingVerification'],'site');const u=https(data.site.url,'Public site URL');if(data.site.url!==u.origin||!u.hostname.includes('.')||u.pathname!=='/'||u.search||u.hash||u.port||u.hostname==='localhost'||u.hostname.endsWith('.local')||u.hostname.endsWith('.localhost')||/^\d+\.\d+\.\d+\.\d+$/.test(u.hostname)||u.hostname.includes(':'))throw new Error('Public site URL must be a public domain origin, without a path or port.');bool(data.site.index,'Site indexing');
  for(const key of ['googleVerification','bingVerification']){text(data.site[key],key,300,true);if(data.site[key]&&!/^[a-zA-Z0-9_-]+$/.test(data.site[key]))throw new Error(`${key}: paste only the verification token, not the HTML tag.`);}
  own(data.profile,['name','shortName','role','description','email','phone','availability','linkedin','github'],'profile');for(const [key,value] of Object.entries(data.profile))text(value,'Profile '+key,key==='description'?500:200);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.profile.email))throw new Error('Enter a valid contact email.');for(const k of ['linkedin','github'])https(data.profile[k],k);
  own(data.pages,routes,'pages');
  for(const [route,page] of Object.entries(data.pages)){own(page,['title','description','canonical','index','image','headingLine1','headingLine2','intro'],route);text(page.title,route+' title',100);text(page.description,route+' description',350);if(!routes.includes(page.canonical))throw new Error(`${route}: canonical must be an existing page path.`);bool(page.index,route+' indexing');asset(page.image,route+' social image',root);text(page.headingLine1,route+' heading',70,route.startsWith('/work/'));text(page.headingLine2,route+' heading second line',70,true);text(page.intro,route+' introduction',650,route.startsWith('/work/'));}
  if(!Array.isArray(data.projects)||data.projects.length!==slugs.length||new Set(data.projects.map(p=>p.slug)).size!==slugs.length)throw new Error('Preserve the four existing project records.');
  for(const p of data.projects){const keys=['slug','title','client','role','period','category','featured','image','screens','summary','outcome','stack','links','metrics','context','approach','build','results','reflection'];const required=keys.filter(k=>!['featured','screens','links'].includes(k));if(!p||typeof p!=='object')throw new Error('Invalid project.');for(const k of Object.keys(p))if(!keys.includes(k))throw new Error(`Unknown project field ${k}`);for(const k of required)if(!(k in p))throw new Error(`Missing project field ${k}`);if(!slugs.includes(p.slug))throw new Error('Project slugs cannot be changed here.');for(const k of ['title','client','role','period','summary','outcome'])text(p[k],p.slug+' '+k,k==='summary'?700:250);if(!['Mobile','Web','WordPress','Backend'].includes(p.category))throw new Error('Unknown project category.');if('featured'in p)bool(p.featured,'Featured');asset(p.image,'Project image',root);if(p.screens){list(p.screens,'Screens',15);p.screens.forEach(v=>asset(v,'Screenshot',root));}for(const k of ['stack','context','approach','results','reflection'])list(p[k],p.slug+' '+k);if(p.links){for(const [k,v]of Object.entries(p.links)){if(!['appstore','playstore','website'].includes(k))throw new Error('Unknown project link.');https(v,'Project link');}}if(!Array.isArray(p.metrics)||p.metrics.length>10)throw new Error('Invalid project facts.');for(const m of p.metrics){own(m,['label','value'],'Fact');text(m.label,'Fact label',100);text(m.value,'Fact value',200);}if(!Array.isArray(p.build)||!p.build.length||p.build.length>15)throw new Error('Invalid build sections.');for(const s of p.build){own(s,['heading','body'],'Build section');text(s.heading,'Build heading',200);list(s.body,'Build paragraphs');}}
  return data;
}
export function auditSettings(data){const findings=[];const add=(level,page,message)=>findings.push({level,page,message});const titles=new Map();for(const [route,p]of Object.entries(data.pages)){if(p.title.length<25||p.title.length>65)add('review',route,`Title is ${p.title.length} characters. Check clarity and likely truncation; length alone is not a ranking rule.`);if(p.description.length<100||p.description.length>165)add('review',route,`Description is ${p.description.length} characters. Review its completeness and search preview.`);if(titles.has(p.title))add('error',route,'Title duplicates '+titles.get(p.title));titles.set(p.title,route);if(!p.index)add('info',route,'Page is set to noindex and omitted from the sitemap.');if(p.canonical!==route){add('review',route,'Canonical points to '+p.canonical+'; this URL will be omitted from the sitemap.');if(!data.pages[p.canonical].index)add('error',route,'Canonical target is set to noindex.');}}
if(!data.site.index)add('review','Site','Public pages are set to noindex and the sitemap will be empty.');if(!data.site.googleVerification)add('info','Search Console','No HTML verification token is configured. DNS verification may already exist; ownership status is not checked here.');return findings;}
