import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {randomBytes,createHash,timingSafeEqual} from 'node:crypto';
import {validateContent,auditSettings} from '../seo/config.mjs';import {runAudit} from '../seo/audit.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');const file=path.join(root,'src/content/managed.json');const port=Number(process.env.CONTENT_EDITOR_PORT||3102);if(!Number.isInteger(port)||port<1024||port>65535)throw new Error('Choose a valid CONTENT_EDITOR_PORT.');
const token=randomBytes(32).toString('hex');const hosts=new Set([`127.0.0.1:${port}`,`localhost:${port}`]);const revision=raw=>createHash('sha256').update(raw).digest('hex');let saving=false,auditing=false;
const read=async()=>{const raw=await fs.readFile(file,'utf8');return{content:JSON.parse(raw),revision:revision(raw)};};
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','X-Robots-Tag':'noindex, nofollow','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'"});res.end(type.startsWith('application/json')?JSON.stringify(body):body);}
async function body(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>500000)throw new Error('Request exceeds 500 KB.');chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
function authorized(req){const t=req.headers['x-editor-token'];return typeof t==='string'&&t.length===token.length&&timingSafeEqual(Buffer.from(t),Buffer.from(token));}
const server=http.createServer(async(req,res)=>{try{if(!hosts.has(req.headers.host))return send(res,403,{error:'Host not allowed.'});const url=new URL(req.url,`http://${req.headers.host}`);if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`)return send(res,403,{error:'Origin not allowed.'});if(req.headers['sec-fetch-site']==='cross-site'&&url.pathname.startsWith('/api/'))return send(res,403,{error:'Cross-site request refused.'});
if(req.method==='GET'&&url.pathname==='/'){const html=(await fs.readFile(path.join(root,'scripts/editor/index.html'),'utf8')).replace('EDITOR_TOKEN',token);return send(res,200,html,'text/html; charset=utf-8');}
if(req.method==='GET'&&['/editor.css','/editor.js'].includes(url.pathname)){const isJs=url.pathname.endsWith('.js');return send(res,200,await fs.readFile(path.join(root,'scripts/editor',isJs?'editor.js':'editor.css'),'utf8'),isJs?'text/javascript; charset=utf-8':'text/css; charset=utf-8');}
if(url.pathname.startsWith('/api/')&&!authorized(req))return send(res,403,{error:'Editor session expired or missing. Reload this local editor.'});
if(req.method==='GET'&&url.pathname==='/api/content'){const state=await read();return send(res,200,{...state,findings:auditSettings(state.content)});}
if(req.method==='PUT'&&url.pathname==='/api/content'){if(req.headers['content-type']!=='application/json')return send(res,415,{error:'Use application/json.'});if(saving)return send(res,409,{error:'Another save is in progress. Try again.'});saving=true;try{const input=await body(req);const current=await read();if(input.revision!==current.revision)return send(res,409,{error:'Content changed in another tab or file. Export your edits, then reload before saving.'});validateContent(input.content,root);const text=JSON.stringify(input.content,null,2)+'\n';const backups=path.join(root,'.content-backups');await fs.mkdir(backups,{recursive:true});await fs.copyFile(file,path.join(backups,`managed-${Date.now()}-${randomBytes(3).toString('hex')}.json`));const temp=file+'.'+randomBytes(8).toString('hex')+'.tmp';try{const handle=await fs.open(temp,'wx');try{await handle.writeFile(text);await handle.sync();}finally{await handle.close();}await fs.rename(temp,file);}finally{await fs.rm(temp,{force:true});}return send(res,200,{revision:revision(text),findings:auditSettings(input.content),message:'Saved to project files. Development previews update automatically; rebuild and deploy to publish.'});}finally{saving=false;}}
if(req.method==='POST'&&url.pathname==='/api/audit'){if(auditing)return send(res,409,{error:'An audit is already running.'});const input=await body(req);if(![3000,3001,3101].includes(Number(input.port)))return send(res,400,{error:'Choose a supported local preview port.'});auditing=true;try{const{content}=await read();return send(res,200,await runAudit(`http://127.0.0.1:${Number(input.port)}`,content));}finally{auditing=false;}}
return send(res,404,{error:'Not found.'});}catch(e){return send(res,400,{error:e.message||'Request failed.'});}});
server.requestTimeout=15000;server.headersTimeout=10000;server.listen(port,'127.0.0.1',()=>console.log(`Content & SEO editor: http://127.0.0.1:${port}\nLocal files only. No database. Rebuild and deploy to publish changes.`));
